class PackageJson
  VERSION: String

  class Error < StandardError
  end

  class NotImplementedError < Error
  end

  attr_reader manager: Managers::Base
  attr_reader path: String

  def initialize: (?(:npm | :yarn_classic | :pnpm) package_manager, ?String path_to_directory) -> PackageJson

  def fetch: (String key, ?untyped default) -> (String | Hash[String, untyped] | Array[untyped])

  def merge!: () { (Hash[String | Symbol, untyped]) -> Hash[String | Symbol, untyped] } -> void

  private

  @path: String

  def package_json_path: () -> String

  def ensure_package_json_exists: ((:npm | :yarn_classic | :pnpm) package_manager) -> void

  def read_package_json: () -> void

  def write_package_json: (_ToJson contents) -> void
end
