class PackageJson
  VERSION: String

  class Error < StandardError
  end

  class NotImplementedError < Error
  end

  attr_reader manager: Managers::Base
  attr_reader directory: String

  def self.fetch_default_fallback_manager: () -> Symbol

  def self.read: (?String path_to_directory, ?package_manager: (:npm | :yarn_berry | :yarn_classic | :pnpm | :bun)) -> PackageJson

  def initialize: (?String path_to_directory, ?package_manager: (:npm | :yarn_berry | :yarn_classic | :pnpm | :bun)) -> PackageJson

  def fetch: (String key, ?untyped default) -> (String | Hash[String, untyped] | Array[untyped])

  def merge!: () { (Hash[String | Symbol, untyped]) -> Hash[String | Symbol, untyped] } -> void

  private

  @directory: String

  def determine_package_manager: (Symbol fallback_manager) -> Symbol

  def new_package_manager: (Symbol package_manager_name) -> Managers::Base

  def package_json_path: () -> String

  def ensure_package_json_exists: ((:npm | :yarn_berry | :yarn_classic | :pnpm | :bun) package_manager) -> void

  def read_package_json: () -> void

  def write_package_json: (_ToJson contents) -> void
end
