class PackageJson
  module Managers
    class Base
      def initialize: (PackageJson package_json, manager_cmd: String) -> self

      def install: (
          ?frozen: bool,
          ?ignore_scripts: bool,
          ?legacy_peer_deps: bool,
          ?omit_optional_deps: bool
        ) -> (bool | nil)

      def install!: (
          ?frozen: bool,
          ?ignore_scripts: bool,
          ?legacy_peer_deps: bool,
          ?omit_optional_deps: bool
        ) -> void

      def native_install_command: (
          ?frozen: bool,
          ?ignore_scripts: bool,
          ?legacy_peer_deps: bool,
          ?omit_optional_deps: bool
        ) -> String

      def add: (
          Array[String] packages,
          ?type: :production | :dev | :optional | :peer,
          ?ignore_scripts: bool,
          ?legacy_peer_deps: bool,
          ?omit_optional_deps: bool
        ) -> (bool | nil)

      def add!: (
          Array[String] packages,
          ?type: :production | :dev | :optional | :peer,
          ?ignore_scripts: bool,
          ?legacy_peer_deps: bool,
          ?omit_optional_deps: bool
        ) -> void

      def remove: (
          Array[String] packages,
          ?ignore_scripts: bool,
          ?legacy_peer_deps: bool,
          ?omit_optional_deps: bool
        ) -> (bool | nil)

      def remove!: (
          Array[String] packages,
          ?ignore_scripts: bool,
          ?legacy_peer_deps: bool,
          ?omit_optional_deps: bool
        ) -> void

      def run: (
          String script_name,
          ?Array[String] args,
          ?silent: bool
        ) -> (bool | nil)

      def run!: (
          String script_name,
          ?Array[String] args,
          ?silent: bool
        ) -> void

      def native_run_command: (
          String script_name,
          ?Array[String] args,
          ?silent: bool
        ) -> String

      private

      @manager_cmd: String
      @package_json: PackageJson

      def build_full_cmd: (String cmd, Array[String] args) -> String

      def raw: (String cmd, Array[String] args) -> (bool | nil)
    end
  end
end
