class PackageJson
  module Managers
    class PnpmLike < Base
      def initialize: (PackageJson package_json) -> self

      def version: () -> String

      def install: (
          ?frozen: bool,
          ?ignore_scripts: bool,
          ?legacy_peer_deps: bool,
          ?omit_optional_deps: bool
        ) -> (bool | nil)

      def install!: (
          ?frozen: bool,
          ?ignore_scripts: bool,
          ?legacy_peer_deps: bool,
          ?omit_optional_deps: bool
        ) -> void

      def native_install_command: (
          ?frozen: bool,
          ?ignore_scripts: bool,
          ?legacy_peer_deps: bool,
          ?omit_optional_deps: bool
        ) -> Array[String]

      def add: (
          Array[String] packages,
          ?type: :production | :dev | :optional | :peer,
          ?ignore_scripts: bool,
          ?legacy_peer_deps: bool,
          ?omit_optional_deps: bool
        ) -> (bool | nil)

      def add!: (
          Array[String] packages,
          ?type: :production | :dev | :optional | :peer,
          ?ignore_scripts: bool,
          ?legacy_peer_deps: bool,
          ?omit_optional_deps: bool
        ) -> void

      def remove: (
          Array[String] packages,
          ?ignore_scripts: bool,
          ?legacy_peer_deps: bool,
          ?omit_optional_deps: bool
        ) -> (bool | nil)

      def remove!: (
          Array[String] packages,
          ?ignore_scripts: bool,
          ?legacy_peer_deps: bool,
          ?omit_optional_deps: bool
        ) -> void

      def run: (
          String script_name,
          ?Array[String] args,
          ?silent: bool
        ) -> (bool | nil)

      def run!: (
          String script_name,
          ?Array[String] args,
          ?silent: bool
        ) -> void

      def native_run_command: (
          String script_name,
          ?Array[String] args,
          ?silent: bool
        ) -> Array[String]

      def native_exec_command: (
          String script_name,
          ?Array[String] args
        ) -> Array[String]

      private

      def build_run_args: (
          String script_name,
          Array[String] args,
          silent: bool
        ) -> Array[String]

      def with_native_args: (
          *(String | nil) extra_args,
          ?frozen: bool | nil,
          ?ignore_scripts: bool | nil,
          ?omit_optional_deps: bool | nil,
          ?_unsupported: Array[untyped]
        ) -> Array[String]

      def package_type_install_flag: (Symbol type) -> String
    end
  end
end
